//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace CashTrack
{
    public class Client
    {
        private int isEnabled;
        private string firstName;
        private string lastName;
        private DateTime birthDate;
        private string email;
        private string password;
        private DateTime createdAt;
        private DateTime updatedAt;
        private DateTime deletedAt;
        private int locationID;

        public Client(string firstName, string lastName, DateTime birthDate, string email, string password, int locationID)
        {
            isEnabled = 1;
            this.firstName = firstName;
            this.lastName = lastName;
            this.birthDate = birthDate;
            this.email = email;
            this.password = password;
            createdAt = DateTime.Now;
            updatedAt = DateTime.Now;
            this.locationID = locationID;
        }


    }
}