//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace CashTrack
{
    public class Company
    {
        private int isEnabled;
        private string name;

        public Company(string name)
        {
            isEnabled = 0;
            this.name = name;
        }
    }
}