//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashTrack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int id { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string zipcode { get; set; }
        public int ClientID { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
