//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace CashTrack
{
    public class Location
    {
        private string city;
        private string address;
        private string zipcode;
        private int clientID;

        public Location(string city, string address, string zipcode)
        {
            this.city = city;
            this.address = address;
            this.zipcode = zipcode;
        }
    }
}