//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace CashTrack
{
    public class TransactionCategory
    {
        private int isEnabled;
        private string description;

        public TransactionCategory(string description)
        {
            isEnabled = 0;
            this.description = description;
        }
    }
}